version: '3'

services:
  # Django web container for the Django app
  django:
    build:
      context: ./BE/DjangoAPI/
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network
    restart:
      on-failure

  # Database container for PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # pgAdmin container for database management
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    container_name: 'nginx'
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./Front:/usr/share/nginx/html
    ports:
      - "3000:3000"
    networks:
      - app-network


# Store data persistently in named volumes
volumes:
  postgres_data:

# Define the networks
networks:
  app-network:
    driver: bridge
